name: Deploy Weather App

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Replace API key placeholder
      run: sed -i 's/YOUR_API_KEY_PLACEHOLDER/${{ secrets.WEATHER_API_KEY }}/g' config.js

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./
